/* ================================
   SANDWEEJI — Static Seed Data
   Replace with live Firestore data
   ================================ */
import type { Category, Product, Review, RestaurantSettings } from './types'

export const WHATSAPP_NUMBER = '+96170206686'
export const INSTAGRAM_URL   = 'https://www.instagram.com/sandeweeji/'
export const FACEBOOK_URL    = 'https://www.facebook.com/612075731998703'

export const RESTAURANT_SETTINGS: RestaurantSettings = {
  nameEn: 'Sandweeji',
  nameAr: 'ساندويجي',
  whatsappNumber: WHATSAPP_NUMBER,
  instagramUrl: INSTAGRAM_URL,
  facebookUrl: FACEBOOK_URL,
  phone: '+96170206686',
  addressEn: 'Abi Samra, Tripoli, Lebanon',
  addressAr: 'أبي سمرا، طرابلس، لبنان',
  lat: 34.4425,
  lng: 35.8447,
  openingHours: [
    { day: 'Monday',    dayAr: 'الإثنين',    openTime: '11:00', closeTime: '23:00', closed: false },
    { day: 'Tuesday',   dayAr: 'الثلاثاء',   openTime: '11:00', closeTime: '23:00', closed: false },
    { day: 'Wednesday', dayAr: 'الأربعاء',  openTime: '11:00', closeTime: '23:00', closed: false },
    { day: 'Thursday',  dayAr: 'الخميس',    openTime: '11:00', closeTime: '00:00', closed: false },
    { day: 'Friday',    dayAr: 'الجمعة',    openTime: '11:00', closeTime: '01:00', closed: false },
    { day: 'Saturday',  dayAr: 'السبت',     openTime: '11:00', closeTime: '01:00', closed: false },
    { day: 'Sunday',    dayAr: 'الأحد',     openTime: '12:00', closeTime: '23:00', closed: false },
  ],
  heroSlides: [],
  seoTitle: 'Sandweeji | Best Burgers & Shawarma in Tripoli, Lebanon',
  seoDescription: 'Sandweeji — premium street food in Tripoli. Burgers, shawarma, crispy chicken & more. Order on WhatsApp.',
}

export const CATEGORIES: Category[] = [
  { id: 'burgers',   nameEn: 'Burgers',         nameAr: 'برغر',      emoji: '🍔', order: 1, visible: true },
  { id: 'shawarma',  nameEn: 'Shawarma',        nameAr: 'شاورما',    emoji: '🌯', order: 2, visible: true },
  { id: 'chicken',   nameEn: 'Crispy Chicken',  nameAr: 'دجاج مقرمش', emoji: '🍗', order: 3, visible: true },
  { id: 'sides',     nameEn: 'Sides',           nameAr: 'مقبلات',    emoji: '🍟', order: 4, visible: true },
  { id: 'drinks',    nameEn: 'Drinks',          nameAr: 'مشروبات',   emoji: '🥤', order: 5, visible: true },
  { id: 'meals',     nameEn: 'Meal Deals',      nameAr: 'وجبات',     emoji: '🎁', order: 6, visible: true },
]

export const PRODUCTS: Product[] = [
  /* ---- BURGERS ---- */
  {
    id: 'b1',
    categoryId: 'burgers',
    nameEn: 'Original Sandweeji Burger',
    nameAr: 'برغر ساندويجي الأصلي',
    descriptionEn: 'Double smash patty, special sauce, caramelized onions, pickles & cheese',
    descriptionAr: 'باتي مضغوط مزدوج، صوص خاص، بصل كراميل، مخلل وجبنة',
    price: 14000,
    image: '/images/classic-burger.png',
    badges: ['popular', 'bestseller'],
    available: true,
    featured: true,
    calories: 680,
    extras: [
      { id: 'e1', nameEn: 'Extra Patty', nameAr: 'باتي إضافي', price: 5000 },
      { id: 'e2', nameEn: 'Extra Cheese', nameAr: 'جبنة إضافية', price: 2000 },
      { id: 'e3', nameEn: 'Bacon', nameAr: 'بيكون', price: 3000 },
    ],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'b2',
    categoryId: 'burgers',
    nameEn: 'Spicy Fire Burger',
    nameAr: 'برغر حار',
    descriptionEn: 'Crispy chicken patty, jalapeños, spicy mayo, lettuce & tomato',
    descriptionAr: 'باتي دجاج مقرمش، فلفل حار، مايونيز حار، خس وطماطم',
    price: 15000,
    image: '/images/classic-burger.png',
    badges: ['spicy', 'new'],
    available: true,
    featured: false,
    calories: 720,
    extras: [
      { id: 'e2', nameEn: 'Extra Cheese', nameAr: 'جبنة إضافية', price: 2000 },
    ],
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'b3',
    categoryId: 'burgers',
    nameEn: 'Classic Smash Burger',
    nameAr: 'برغر كلاسيكي',
    descriptionEn: 'Single smash patty, American cheese, mustard, ketchup & pickles',
    descriptionAr: 'باتي مفرد، جبنة أمريكية، مسطردة، كاتشب ومخلل',
    price: 11000,
    image: '/images/classic-burger.png',
    badges: [],
    available: true,
    featured: false,
    calories: 540,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  /* ---- SHAWARMA ---- */
  {
    id: 's1',
    categoryId: 'shawarma',
    nameEn: 'Chicken Shawarma',
    nameAr: 'شاورما دجاج',
    descriptionEn: 'Marinated chicken, garlic sauce, pickles & fresh veggies in flatbread',
    descriptionAr: 'دجاج متبل، صوص ثوم، مخلل وخضار طازج في خبز مرقوق',
    price: 13000,
    image: '/images/shawarma-wrap.png',
    badges: ['popular'],
    available: true,
    featured: true,
    calories: 580,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's2',
    categoryId: 'shawarma',
    nameEn: 'Meat Shawarma',
    nameAr: 'شاورما لحم',
    descriptionEn: 'Seasoned beef & lamb mix, tahini sauce, tomatoes & parsley',
    descriptionAr: 'لحم بقري وغنم متبل، طحينة، طماطم وبقدونس',
    price: 16000,
    image: '/images/shawarma-wrap.png',
    badges: ['bestseller'],
    available: true,
    featured: true,
    calories: 650,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  /* ---- CRISPY CHICKEN ---- */
  {
    id: 'c1',
    categoryId: 'chicken',
    nameEn: 'Crispy Chicken Sandwich',
    nameAr: 'ساندويش دجاج مقرمش',
    descriptionEn: 'Buttermilk fried chicken, pickles, coleslaw & house sauce on brioche',
    descriptionAr: 'دجاج مقلي بالبطرميلك، مخلل، كول سلو وصوص البيت على خبز بريوش',
    price: 16000,
    image: '/images/crispy-chicken.png',
    badges: ['new', 'popular'],
    available: true,
    featured: true,
    calories: 740,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'c2',
    categoryId: 'chicken',
    nameEn: 'Nashville Hot Chicken',
    nameAr: 'دجاج ناشفيل الحار',
    descriptionEn: 'Extra crispy chicken drenched in Nashville hot sauce, pickles & honey',
    descriptionAr: 'دجاج مقرمش مغطى بصوص ناشفيل الحار، مخلل وعسل',
    price: 17000,
    image: '/images/crispy-chicken.png',
    badges: ['spicy', 'new'],
    available: true,
    featured: false,
    calories: 810,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  /* ---- SIDES ---- */
  {
    id: 'sd1',
    categoryId: 'sides',
    nameEn: 'Loaded Fries',
    nameAr: 'بطاطا محشية',
    descriptionEn: 'Crispy fries topped with cheese sauce, crispy chicken bits & jalapeños',
    descriptionAr: 'بطاطا مقرمشة مع صوص الجبنة، قطع دجاج مقرمش وجالابينو',
    price: 10000,
    image: '/images/loaded-fries.png',
    badges: ['popular'],
    available: true,
    featured: false,
    calories: 520,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sd2',
    categoryId: 'sides',
    nameEn: 'Classic Fries',
    nameAr: 'بطاطا كلاسيك',
    descriptionEn: 'Golden crispy fries seasoned with our house spice blend',
    descriptionAr: 'بطاطا ذهبية مقرمشة متبلة بمزيجنا الخاص',
    price: 6000,
    image: '/images/loaded-fries.png',
    badges: [],
    available: true,
    featured: false,
    calories: 380,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  /* ---- DRINKS ---- */
  {
    id: 'd1',
    categoryId: 'drinks',
    nameEn: 'Fresh Lemonade',
    nameAr: 'ليموناضة طازجة',
    descriptionEn: 'House-squeezed lemonade with fresh mint & crushed ice',
    descriptionAr: 'ليمون طازج مع نعناع وثلج مكسر',
    price: 5000,
    image: '/images/lemonade.png',
    badges: [],
    available: true,
    featured: false,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  /* ---- MEALS ---- */
  {
    id: 'm1',
    categoryId: 'meals',
    nameEn: 'Original Burger Meal',
    nameAr: 'وجبة البرغر الأصلي',
    descriptionEn: 'Original Sandweeji Burger + Classic Fries + Drink of your choice',
    descriptionAr: 'برغر ساندويجي الأصلي + بطاطا كلاسيك + مشروب من اختيارك',
    price: 22000,
    image: '/images/classic-burger.png',
    badges: ['meal', 'popular'],
    available: true,
    featured: true,
    calories: 1060,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'm2',
    categoryId: 'meals',
    nameEn: 'Shawarma Meal',
    nameAr: 'وجبة الشاورما',
    descriptionEn: 'Chicken Shawarma + Classic Fries + Fresh Lemonade',
    descriptionAr: 'شاورما دجاج + بطاطا كلاسيك + ليموناضة طازجة',
    price: 20000,
    image: '/images/shawarma-wrap.png',
    badges: ['meal'],
    available: true,
    featured: true,
    calories: 960,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    authorName: 'Ahmad K.',
    rating: 5,
    textEn: 'Best burger in all of Tripoli! The smash patty is perfectly crispy and the sauce is addictive.',
    textAr: 'أفضل برغر في كل طرابلس! الباتي مقرمش بشكل مثالي والصوص مدمن.',
    date: '2024-12-01',
  },
  {
    id: 'r2',
    authorName: 'Sarah M.',
    rating: 5,
    textEn: 'The shawarma here is on another level. Fresh ingredients, generous portions, amazing flavors.',
    textAr: 'الشاورما هنا على مستوى آخر. مكونات طازجة، حصص سخية، نكهات رائعة.',
    date: '2024-12-05',
  },
  {
    id: 'r3',
    authorName: 'Omar T.',
    rating: 5,
    textEn: 'Nashville Hot Chicken sandwich is insane. Crispy, spicy, and the honey drizzle is genius.',
    textAr: 'ساندويش دجاج ناشفيل الحار جنوني. مقرمش وحار والعسل لمسة عبقرية.',
    date: '2024-12-10',
  },
  {
    id: 'r4',
    authorName: 'Lara H.',
    rating: 5,
    textEn: 'Fast delivery, hot food, perfect packaging. The loaded fries are a must-try!',
    textAr: 'توصيل سريع، طعام ساخن، تغليف مثالي. البطاطا المحشية يجب تجربتها!',
    date: '2024-12-12',
  },
  {
    id: 'r5',
    authorName: 'Rami N.',
    rating: 5,
    textEn: 'Consistently great food every single time. Sandweeji never disappoints!',
    textAr: 'طعام رائع في كل مرة. ساندويجي لا يخذل أبد��ً!',
    date: '2024-12-15',
  },
]
